### ISSUE TITLE
Parameterize # of GameServer creations/deletions

### ISSUE THREAD

**Issue by dgkanatsios** [PlayFab/thundernetes#157]
#141 introduced functionality to batch create/delete the amount of GameServers to allow the GameServerBuild reconciler to properly update its status. At the moment, the number of items to be included in a Batch is a const, we should parameterize that, maybe with two env variables on the controller.

**Comment by ujljg675** [comment]
> #141 introduced functionality to batch create/delete the amount of GameServers to allow the GameServerBuild reconciler to properly update its status. At the moment, the number of items to be included in a Batch is a const, we should parameterize that, maybe with two env variables on the controller.
