### ISSUE TITLE
Project rename

### ISSUE THREAD

**Issue by dgkanatsios** [PlayFab/thundernetes#177]
As Thundernetes is a code name, we should come up with a new name for the project well before 1.0.

**Comment by eYeMirR0rr0RriMeYe** [comment]
`g```
~~~~
````

**Comment by Beelzenef** [comment]
what about GameStorming? 😋

**Comment by ClaytonHunsinger** [comment]
How about Thor. 
Or perhaps Stormbreaker.

**Comment by eYeMirR0rr0RriMeYe** [comment]
hey its g

**Comment by dgkanatsios** [comment]
Closing till we actually need to do it
