### ISSUE TITLE
please describe when I should use thundernetes and when agones

### ISSUE THREAD

**Issue by dzmitry-lahoda** [PlayFab/thundernetes#195]
i these both are very close to each other, what is the difference? when I should consider using one or the other? will this project support windows in 2022? agones is google official project, is thundernetes officially supported and financed by Microsoft?

**Comment by dgkanatsios** [comment]
hey @dzmitry-lahoda, apologies for the late response, there is a similiar question here: https://github.com/PlayFab/thundernetes/discussions/193 feel free to follow up there. Thundernetes is developed and maintained by people in the XBOX/Azure groups at Microsoft, correct. As mentioned in the main README, it's beta software, we welcome feedback and we'd love external contributions!
Regarding Windows support, I'll follow up on the thread you already responded: https://github.com/PlayFab/thundernetes/issues/8

Closing, feel free to re-open or create a new issue if necessary. Thanks!
