### ISSUE TITLE
Consider Host Networking mode for pods

### ISSUE THREAD

**Issue by khaines** [PlayFab/thundernetes#22]
Currently the game server pods are using host port mapping to accept communication. This process incurs performance overhead from the NAT translations from the host network to the container network. Switching the game server pods to use the host network  directly will remove this overhead. 

However, given the current architecture there are some complications that need to be handled. For example the side car container would also be on the host network, thus exposing it externally on the node's IP.  As currently the controller communicates to the side car for state changes, this will need to be secured first.

**Comment by dgkanatsios** [comment]
#31 fixes the issue mentioned on the last sentence "controller communicates to the side car for state changes", since it introduces Kubernetes watch for the sidecar.

**Comment by dgkanatsios** [comment]
this will be possible by #97, which eliminates the sidecar in favor of a DaemonSet
