### ISSUE TITLE
Upgrading your game server

### ISSUE THREAD

**Issue by davidop** [PlayFab/thundernetes#231]
### about upgradings

To update a game server (whether to update the image you're using or whatever), the[ documentation recommends creating a new game server build](https://playfab.github.io/thundernetes/howtos/upgradebuild.html#upgrading-your-game-server) with the relevant updates

Does this indicate that [deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) are not necessary?

How do we tell our game player/client the new build ID, without having to log out of their game session?

**Comment by dgkanatsios** [comment]
> Does this indicate that [deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) are not necessary?
Correct, the only thing you need to deploy is a GameServerBuild. 

> How do we tell our game player/client the new build ID, without having to log out of their game session?
Unfortunately, this is something you need to handle in-game. How long are your game sessions? Usually, game servers have short sessions (like 10 minutes or so), so it's safe to stop allocating game servers on the old GameServerBuild and start allocating on the new one. In this case, existing sessions will continue till they finish.

Let me know if this doesn't answer your question, happy to elaborate more!

**Comment by davidop** [comment]
Thanks. No more question
