### ISSUE TITLE
questions on tooling and architecture

### ISSUE THREAD

**Issue by Beelzenef** [PlayFab/thundernetes#233]
### about K8S components

the [architecture graph](https://playfab.github.io/thundernetes/architecture.html#architecture) is very useful, but I have doubts... is it necessary to deploy replica sets or deployments on the pods (game servers)? or is it totally abstracted?

### tooling

what kind of component is a GameServerBuild? I'm using [LENS](https://k8slens.dev/) to get a better management of the cluster, but theres lack of information about custom/thundernetes components

are you aware of any similar tool with which to manage Thundernetes on IDE?

**Comment by dgkanatsios** [comment]
thanks for reaching out!

on the K8s components, what you deploy is just a [GameServerBuild](https://playfab.github.io/thundernetes/gameserverbuild.html). Thundernetes will take care of deploying the necessary Pods for your game server instances. 

on the tooling, a GameServerBuild is a Kubernetes Custom Resource Definition (CRD) [link 1](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) and [link 2](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/). Unfortunately, I'm not familiar with Lens, does it support CRDs? I know for sure that Visual Studio Code extension for Kubernetes supports them.

**Comment by Beelzenef** [comment]
As far as I know, LENS does not support CRDs or there are many bugs related to this functionality. We will get acquainted with the components through the terminal + VS Code, thank you very much!
