### ISSUE TITLE
thundernetes-standby-forecaster:0.5 image Not Found

### ISSUE THREAD

**Issue by nikawang** [PlayFab/thundernetes#359]
**Describe the bug**

**To Reproduce**
1. Try to deploy Intelligent scaling
2. See error " Back-off pulling image "gcr.io/playfab/thundernetes-standby-forecaster:0.5""

**Expected behavior**
The sample can be setup

**Additional context**
Just take a look at the [Makefile](https://github.com/PlayFab/thundernetes/blob/main/Makefile#L12), no thundernetes-standby-forecaster was build

**Comment by dgkanatsios** [comment]
Hi there! Looks like this is a typo, can you try “ docker pull ghcr.io/playfab/thundernetes-standby-forecaster:0.5.0”?

**Comment by nikawang** [comment]
Oh Thanks @dgkanatsios , there it is. The tag ["0.5"](https://github.com/PlayFab/thundernetes/blob/main/samples/standby-forecaster/forecaster.yaml#L39) in the sample yaml should the "0.5.0". You can close this issue. Thanks very much

**Comment by dgkanatsios** [comment]
Thank you, we’ll fix it ASAP! Let us know if you bump into any issues
