### ISSUE TITLE
Scale test Thundernetes

### ISSUE THREAD

**Issue by allenlsy** [PlayFab/thundernetes#400]
**Is your feature request related to a problem? Please describe.**

This is a non-feature request. We want an automated process of running scale test, to understand the system better and discover potential pitfalls.

At this stage, the scale test and its further research should answer these questions:

- [ ] 1. benchmark: scale up GSs, and monitor provisioning time. This will be the benchmark for performance improvement
- [ ] 2. usability: any ways to configure how many pending pods we have while scaling? how to do that
- [ ] 3. performance: how to scale up AND down quickly, to satisfy user experience and saving cost
- [ ] 4. scalability: how many pods can be provisioning/running at the same time on Thundernetes

**Describe the solution you'd like**

sub task 1), we will use the default configuration of Thundernetes, and scale up to 100, 200, 400, 800 game servers respectively and measure the time needed to complete the provisioning job. This data will be used to evaluated performance improvements.

sub task 4) this need to be discussed in two scenarios:

1. when all game servers are being provisioned. I assume this is the moment when the system is most buzy. 
2. after all game servers are provisioned and running on their own  

By separating the scenarios, it helps us understanding the bottleneck of the system

**Comment by dgkanatsios** [comment]
Done in #413
