### ISSUE TITLE
try different game engines on thundernetes

### ISSUE THREAD

**Issue by dgkanatsios** [PlayFab/thundernetes#60]
We should validate various game engines (Unreal/Unity) in thundernetes. We can borrow some from https://github.com/PlayFab/gsdk and https://github.com/PlayFab/MpsSamples repos

- [ ] Unreal
- [x] Unity

**Comment by AmieDD** [comment]
I can work on validating this with Unreal Engine this week. :)

**Comment by dgkanatsios** [comment]
I'll try to run this sample https://github.com/PlayFab/MpsSamples/tree/master/UnityMirror as well.
