### ISSUE TITLE
CRUD API for GameServerBuild/GameServer CRs

### ISSUE THREAD

**Issue by dgkanatsios** [PlayFab/thundernetes#79]
We should create CRUD APIs for GameServerBuild and GameServer CRs. This API should also serve as a basis for #16

**Comment by AmieDD** [comment]
Are we thinking of writing this API in go? 

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
)

type Article struct {
	Title   string `json:"Title"`
	Desc    string `json:"desc"`
	Content string `json:"content"`
}

type Articles []Article

func allArticles(w http.ResponseWriter, r *http.Request) {
	articles := Articles{
		Article{Title: "thundernetes", Desc: "thundernetes API", Content: "Howdy"},
	}
	fmt.Println("thundernetes endpoint Hit: All Articles Endpoint")
	fmt.Println("All Articles: ", articles)
	json.NewEncoder(w).Encode(articles)
}

func homePage(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "thundernetes homepage endpoint hit")
}

func handleRequests() {
	http.HandleFunc("/", homePage)
	http.HandleFunc("/articles", allArticles)
	log.Fatal(http.ListenAndServe(":8081", nil))
}

func main() {
	handleRequests()
}
```

**Comment by dgkanatsios** [comment]
yeah, I'd prefer it. It would easily fetch the CRD types from this repo. .NET is kinda tricky to do, check here for some code of the original sidecar (which was written in .NET) https://github.com/PlayFab/thundernetes/blob/72d501ad20dcc5ca76773b6fd6ea18cac62b5185/sidecar-netcore/Controllers/ThundernetesController.cs

**Comment by dgkanatsios** [comment]
The APIs we need
- CreateGameServerBuild
- ListGameServerBuilds
- GetGameServerBuild
- DeleteGameServerBuild
- ListGameServersForBuild
- GetGameServer
- DeleteGameServer 
- ListGameServerDetailsForGameServerBuild
- GetGameServerDetailForGameServer

comments
- GameServerBuilds are supposed to be immutable (so no update)
- we need DeleteGameServer in case the game server process is stuck

**Comment by dgkanatsios** [comment]
The API has been created and integrated, we should create some end to end tests as well. Plus, we'd need to modify our publishing pipeline to publish a container image as well. Keeping this open till we complete these tasks.

**Comment by dgkanatsios** [comment]
Opened #123 to cover the missing end to end tests for the GameServer API, closing this.
