### ISSUE TITLE
Windows container support

### ISSUE THREAD

**Issue by dgkanatsios** [PlayFab/thundernetes#8]
Investigate what would be needed for thundernetes to work with Windows game servers (containers).

**Comment by dzmitry-lahoda** [comment]
until aks 1.23 containerd windows is really not maintanable.

**Comment by dzmitry-lahoda** [comment]
so basic need to avoid ms windows bugs with cni and docker and huge resource consumption is to run aks 1.23 plus with host process isolation. 
prom and fluentd may be will work, not sure. so ai does not work for sure in my case.

**Comment by dgkanatsios** [comment]
hey @dzmitry-lahoda, thanks for reaching out. We eventually plan to work on Windows support. Can you clarify on the issues on AKS pre-1.23 for Windows Node Groups?

**Comment by dzmitry-lahoda** [comment]
ms pre containerd has 2 severe bugs and lack of support of monutoring/loga. starting aks 1.23 it kinda works. so if you going to support windows is may be point to support 1.23 and up only.

**Comment by dzmitry-lahoda** [comment]
ms support aware of bugs and response was upgrade to 1.23
